FROM dockerhub.capitalonline.net/devops_project/power_collect:3.11-slim
RUN mkdir -p /app
ADD . /app
WORKDIR /app/project
COPY requirement.txt /app/project/requirement.txt
RUN pip install -r requirement.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
COPY . /app/
EXPOSE 8000
CMD
